- contracts/interfaces/FeedRegistryInterface.sol
- contracts/oracles/BinanceOracle.sol
- contracts/oracles/mocks/MockBinanceFeedRegistry.sol
- contracts/oracles/mocks/MockBinanceOracle.sol
- deploy/oracles.ts
- test/BinanceOracle.ts
- yarn.lock
> Binance Oracle Integration

- contracts/ResilientOracle.sol
- contracts/interfaces/OracleInterface.sol
- contracts/oracles/TwapOracle.sol
- contracts/test/MockSimpleOracle.sol
- test/ResilientOracle.ts
Change for isolated-pools repo: https://github.com/VenusProtocol/isolated-pools/pull/55
> Interface to Update Oracle

- contracts/ResilientOracle.sol
- contracts/interfaces/FeedRegistryInterface.sol
- contracts/libraries/PancakeLibrary.sol
- contracts/oracles/BinanceOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
- contracts/oracles/PivotPythOracle.sol
- contracts/oracles/PivotTwapOracle.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/TwapOracle.sol
- contracts/oracles/mocks/MockBinanceFeedRegistry.sol
- contracts/test/VBEP20Harness.sol
- test/BinanceOracle.ts
- test/ChainlinkOracle.ts
- test/PivotPythOracle.ts
- test/PivotTwapOracle.ts
> Fix Oracle Issues

- contracts/oracles/BinanceOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
- contracts/oracles/PivotTwapOracle.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/TwapOracle.sol
- test/BoundValidator.ts
- test/ChainlinkOracle.ts
- test/PivotPythOracle.ts
- test/PivotTwapOracle.ts
- test/utils/makePair.ts
> Set Token Config using Underlying Asset Address

- package.json
Bumps version to 1.2.1
This version contains an interface for the Price Oracle that can be consumed by contracts using price oracles
> chore: bump version to 1.2.3

- contracts/interfaces/PythInterface.sol
- contracts/oracles/PythOracle.sol
- contracts/test/MockPyth.sol
- package.json
- test/PivotPythOracle.ts
Interfaces updated from: https://github.com/pyth-network/pyth-sdk-solidity/tree/v1.0.1
Resolves #
> Update Pyth Interfaces to 1.0.1

- .gitignore
- .solhint.json
- contracts/PriceOracle.sol
- contracts/interfaces/PythInterface.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/mocks/MockBinanceOracle.sol
- contracts/test/MockPyth.sol
- deploy/oracles.ts
- hardhat.config.ts
- package.json
- test/PivotPythOracle.ts
- Adds Price Oracle interface to package 
- Update PythOracle interface
- Updates oracle deployments
> Release version 1.3.0

- contracts/PriceOracle.sol
- deploy/oracles.ts
- hardhat.config.ts
- package.json
- tsconfig.json
This resolves typescript errors that arise related to hardhat-deploys' ethers extensions.
This version has been released.
> Fix error when compiling and consuming package

- .github/workflows/oracle.yml
- .solcover.js
- package.json
Brings coverage setup to have parity with isolated pools and adds code coverage comments to PRs
> ci: add code coverage comments

- contracts/oracles/TwapOracle.sol
- test/PivotTwapOracle.ts
Changes done as per twap logic issue described [here](https://www.notion.so/TWAP-Solution-b6c2fc77579a47d6a78ae102d70e2a76)
Resolves [VEN-824](https://jira.toolsfdg.net/browse/VEN-824)
> fix: Update twap logic

- .gitignore
- hardhat.config.ts
- package.json
- test/BinanceOracle.ts
- test/BoundValidator.ts
- test/ChainlinkOracle.ts
- test/PivotPythOracle.ts
- test/PivotTwapOracle.ts
- test/ResilientOracle.ts
- yarn.lock
- Use smock.
- Increase coverage for resilient oracle.
> test: use smock and increase coverage

- .prettierignore
- .solhint.json
- .solhintignore
- contracts/PriceOracle.sol
- contracts/ResilientOracle.sol
- contracts/libraries/PancakeLibrary.sol
- contracts/oracles/BinanceOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/TwapOracle.sol
- contracts/oracles/mocks/MockBinanceOracle.sol
- contracts/oracles/mocks/MockChainlinkOracle.sol
- contracts/oracles/mocks/MockPythOracle.sol
- contracts/oracles/mocks/MockTwapOracle.sol
- contracts/test/MockPyth.sol
- contracts/test/MockSimpleOracle.sol
- contracts/test/MockV3Aggregator.sol
- contracts/test/PancakePairHarness.sol
- yarn.lock
Update nat spec for grammar and formatting to follow our [guidelines](https://www.notion.so/Solidity-92e9836010ff4fe5bfa3872df4f8da4e#0818446c8f78405f83cefd6ca9203bb7)
Adds order check to linting and updates contract declaration order to match spec
> [VEN-749] Update nat spec and declaration order

- contracts/oracles/TwapOracle.sol
- deploy/2-configure-feeds.ts
> Netspec and Typescript Lint Fix

- deploy/2-configure-feeds.ts
- package.json
- yarn.lock
Add missing sinon-chai type
Removes generated typechain types from deployment scripts because it will effect consumption of the package as they won't exist
> Resolve type errors for package release

- deploy/2-configure-feeds.ts
- package.json
This PR introduces a fix to the testnet price config for WBNB due to integration tests failure in IL
Resolves #
> fix price config for wbnb price due to integration tests failure in IL

- contracts/Governance/AccessControlManager.sol
- contracts/Governance/AccessControlled.sol
- contracts/Governance/IAccessControlManager.sol
- contracts/ResilientOracle.sol
- contracts/interfaces/PublicResolverInterface.sol
- contracts/interfaces/SIDRegistryInterface.sol
- contracts/oracles/BinanceOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/TwapOracle.sol
- deploy/1-deploy-oracles.ts
- hardhat.config.ts
- package.json
- test/BinanceOracle.ts
- test/BoundValidator.ts
- test/ChainlinkOracle.ts
- test/PivotPythOracle.ts
- test/PivotTwapOracle.ts
- test/ResilientOracle.ts
- test/fork/core-compatibility.ts
- yarn.lock
- Integrated Space ID of Binance oracle to fetch feed registry address
- Fetch real price of VAI
- Added fork tests for vBNB, vXVS, VAI and vLTC
- Integrated ACM
> Core Protocol Compatibility

- deploy/2-configure-feeds.ts
- hardhat.config.ts
- package.json
Fixed lint issues due to which release was failing. Release version 1.6.6
> Fix Lint and Release

- .github/workflows/oracle.yml
- deploy/2-configure-feeds.ts
- yarn.lock
> test: check deployments in CI

- README.md
- package.json
Require node 14.
Node 12 errors because optional chaining is not supported
> fix: require using node 14

- deploy/1-deploy-oracles.ts
> fix: deployment scripts pass check

- test/PivotTwapOracle.ts
Set a one second tolerance to checking timestamp
> fix: set one second tolerance to timestamp check

- .github/workflows/cd.yaml
Since we are checking if a pull request is merged to release we need to also trigger from a pull
> ci: trigger relase from pull

- .github/workflows/cd.yaml
Fix yarn install issue with ethereum-abi checksum
> ci: fix yarn install issue with ethereum-abi checksum

- .github/workflows/cd.yaml
> ci: release on push

- .github/workflows/cd.yaml
> ci: dont persist credentials

- contracts/ResilientOracle.sol
- contracts/interfaces/PythInterface.sol
- contracts/oracles/BinanceOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
- contracts/oracles/PythOracle.sol
- contracts/oracles/TwapOracle.sol
- contracts/test/MockPyth.sol
- test/PivotTwapOracle.ts
- yarn.lock
Resolves issues reported by Certik audit.
> Certik Audit Report Fixes

- .prettierignore
- .releaserc
- commitlint.config.js
Set acceptable commit scopes for linting and releases
> ci: set acceptable commit scopes

- package.json
- Add dist to packge
- remove exports as it doesn't support directories only modules
> fix: remove exports add dist

- test/PivotTwapOracle.ts
Allow for a slight lose of precision when checking values in flaky tests
> test: allow for some precision lose in flaky tests

- docgen-templates/page.hbs
Add doc gen support for contracts and templates
> [VEN-1450] docs: add doc gen support for contracts and templates

- contracts/oracles/TwapOracle.sol
> [VEN-1515]: typo in a comment

- contracts/ResilientOracle.sol
- contracts/oracles/BoundValidator.sol
- contracts/oracles/ChainlinkOracle.sol
> docs: review English

- .github/workflows/ci.yml
- package.json
- yarn.lock
> Troubleshoot package building

- .github/workflows/ci.yml
- package.json
- yarn.lock
Fixes hardhat [issue](https://github.com/NomicFoundation/hardhat/issues/3877) downloading the solidity compiler
> [VEN-1689] fix hardhat compile download issue

- package.json
- yarn.lock
Bumps the governance package version to the latest main release
> chore: bump governance contract version

- README.md
> add badges to the README file and bump a new release

- CHANGELOG.md
- package.json
> Release back

- .github/workflows/ci.yml
Only commit deployment files during export step
> feat: only commit deployment jsons during export

- .gitignore
- hardhat.config.ts
- package.json
- test/BinanceOracle.ts
- test/BoundValidator.ts
- test/ChainlinkOracle.ts
- test/PivotPythOracle.ts
- test/PivotTwapOracle.ts
- test/ResilientOracle.ts
- test/types.ts
- test/utils/makeChainlinkOracle.ts
- test/utils/makePair.ts
- test/utils/makeToken.ts
- test/utils/makeVToken.ts
- tsconfig.json
- yarn.lock
Refactor out waffle in favor of using hardhat deploy in tests
> test: refactor out waffle deployments

- .github/workflows/ci.yml
- deployments/bscmainnet_addresses.json
- deployments/bsctestnet_addresses.json
- deployments/ethereum_addresses.json
- deployments/sepolia_addresses.json
> [VEN-2197]: generate files with addresses of the deployed contracts

- contracts/oracles/BinanceOracle.sol
- test/BinanceOracle.ts
Some network does not support space ID to fetch the feed registry address so this PR contains support of direct feed registry.
Resolves VEN-2211
> [VEN-2211]: support direct feed registry in binance oracle

- .github/workflows/ci.yml
- hardhat.config.ts
Excludes external deployments from exporting to avoid clashing and polluting deployment export
> [VEN-2242]: exclude external deployments when exporting

- contracts/oracles/BinanceOracle.sol
- hardhat.config.ts
- BOV-02 | EMIT EVENT PATTERN INCONSISTENCY
Resolves VEN-2252
> [VEN-2252]: Certik audit fix on Binance Oracle

- .github/workflows/ci.yml
- deployments/opbnbmainnet.json
- deployments/opbnbmainnet_addresses.json
- deployments/opbnbtestnet.json
- deployments/opbnbtestnet_addresses.json
> [VEN-2191]: add opbnbtestnet and opbnbmainnet to the ci step to extract addresses

- package.json
- yarn.lock
> [VEN-1825]: update deps to the stable versions

- deploy/3-vip-based-configuration.ts
- helpers/deploymentConfig.ts
This PR adds the asset config for the oracles for `opbnbmainnet` and fixes the failing VIP configuration script
Resolves #VEN-2202
> [VEN-2202] Asset Config opbnbmainnet

- contracts/interfaces/IAnkrBNB.sol
- contracts/interfaces/IEtherFiLiquidityPool.sol
- contracts/interfaces/IPStakePool.sol
- contracts/interfaces/IPendlePtOracle.sol
- contracts/interfaces/ISFrax.sol
- contracts/interfaces/ISfrxETH.sol
- contracts/interfaces/IStaderStakeManager.sol
- contracts/interfaces/ISynclubStakeManager.sol
- contracts/interfaces/IWBETH.sol
- contracts/oracles/AnkrBNBOracle.sol
- contracts/oracles/BNBxOracle.sol
- contracts/oracles/OneJumpOracle.sol
- contracts/oracles/PendleOracle.sol
- contracts/oracles/SFraxOracle.sol
- contracts/oracles/SFrxETHOracle.sol
- contracts/oracles/SlisBNBOracle.sol
- contracts/oracles/StkBNBOracle.sol
- contracts/oracles/WBETHOracle.sol
- contracts/oracles/WeETHOracle.sol
- contracts/oracles/WstETHOracle.sol
- contracts/oracles/common/CorrelatedTokenOracle.sol
- contracts/test/MockEtherFiLiquidityPool.sol
> [VEN-2540] Quantstamp Audit Fixes

- .eslinttsconfigrc
- deploy/11-deploy-sfrxeth-oracle.ts
- deploy/5-deploy-bnb-lst-oracles.ts
- deploy/6-deploy-wstETH-oracle.ts
- deploy/7-deploy-pendle-oracle.ts
- deploy/8-deploy-weETH-oracle.ts
- package.json
- tsconfig.json
- yarn.lock
> fix: cd issues with zksync config

- .github/workflows/ci.yml
- deploy/4-vip-based-configuration.ts
Update typchain import to fix build
> fix: update type import

- funding.json
> chore: verify repo for Atlas Optimism

- CHANGELOG.md
- package.json
It includes:
* https://github.com/VenusProtocol/oracle/pull/264
> New release

- yarn.lock
> New release (fix)

- contracts/ResilientOracle.sol
- contracts/oracles/common/CorrelatedTokenOracle.sol
> [VEN-3122] Certik audit fixes for capped oracle
